name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Hello
        run: echo "Hello from GitHub Actions!"

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Simulate deployment
        run: echo "Deploying to production..."
