name: Run Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a simple test
        run: |
          echo "Testing started"
          # Here you could run actual test commands, e.g.:
          # python -m unittest discover
          echo "Testing finished successfully"
